keyscroll.js
modules/feed.js
modules/private.js
modules/public.js
modules/tabs.js
modules/thread.js
package.json

h/l: scroll through tabs
j/k: scroll through messages
x: close current tab
Depends on dominictarr/hypertabs#1
There may be a way to do this fitting more with the plugs paradigm, but this is a start anyway.

Add keyboard navigation commands

---

modules/search-box.js
modules/search.js
modules/tabs.js
package.json
style.css
util.js

32f894d: Fixed u.next looping on empty streams <https://github.com/dominictarr/patchbay/pull/8#issuecomment-228944777>
86a4987: Improve speed of channels query
415b47a: Add feed navigation suggestions (press `@` to get a prompt with name/id suggestions)
ba2f9b6: Highlight search terms <https://github.com/dominictarr/patchbay/pull/8#issuecomment-229595810>

Moar search

---

style.css

Try it home, let me know what you think.

Add basic css styling to Patchbay

---

modules/avatar-profile.js
style.css

This is a few minor tweaks of the CSS from earlier. Also I worked on the profile pages a little bit.
Two things to note:
The render on the search bar suggestions still runs into the right side. I did a margin hack to knock it over a bit, but that isn't ideal. The search bar might need to go back on the left side, even though that doesn't seem as balanced.
Also the module hyperlightbox is overwriting styles on the lightbox, so I can't write to them locally. Ideas?

CSS tweaks

---

modules/compose.js
modules/like.js
modules/message-link.js
modules/tabs.js

- Fixed some errors.
- Added a `errors` tab to show new errors. Is this too developer-centric?

Error handling

---

modules/compose.js
modules/search.js
style.css

add a header to the search page to show how many messages have been examined.

Search header

---

modules/index.js
modules/notifications.js
modules/tabs.js

Would we like to see some kind of notifications in Patchbay of mentions and things related to the current uxer?
Possible implementation approach: factor out notifications from ssb-notifier and add a patchbay tab to show them like a feed. This would not take into account watched threads like in Patchwork.

Notifications

---

modules/index.js
modules/invite.js
package.json
sbot-api.js

default should be over websockets (using multiserver) so that they work from the browser.
this also upgrades to ssb-client@4 which is rewritten in terms of multiserver.
it's pretty ugly right now. need to confirm that it actually does work from the browser.
should do though.

WIP: Invites

---

modules/about.js
modules/follow.js
modules/names.js
modules/post.js
modules/private.js
style.css

Add some spaces around things, for aesthetics and to avoid run-on words
Improve some cases of profile naming

Spacing and naming

---

modules/notifications.js

Abort reading the log past the oldest message in your feed, since presumably no one will have mentioned your feed before you started posting on it.
Also fix an error having to do with messages where the branch property is an array

Optimize notifications stream

---

style.css

move search bar to below tabs

---

config.js
index.js
modules/_screen_view.js
modules/about.js
modules/avatar-image.js
modules/blob-url.js
modules/feed.js
modules/follow.js
modules/index.js
modules/markdown.js
modules/names.js
modules/notifications.js
modules/post.js
modules/private.js
modules/split.js
modules/tabs.js
package.json
sbot-api.js

implemented a bunch of things to make liteclients work better.
if you don't have ssb-links installed on your pub, then avatars will break for liteclients that currently work

separate markdown into it's own plugin, and make blobs work on liteclient

---

modules_core/sbot.js

similar to ssbc/scuttlebot#367

pass config.caps to sbot client

---

get-style-for-module.js
modules_basic/about.js
modules_basic/about.mcss
modules_basic/message-author.js
modules_basic/message-author.mcss
modules_basic/message-backlinks.js
modules_basic/message-backlinks.mcss
modules_basic/message.js
modules_basic/message.mcss
modules_basic/post.js
modules_basic/thread.js
modules_basic/timestamp.js
modules_basic/timestamp.mcss
modules_core/index.js
modules_core/style-mixins.js
modules_extra/git.js
package.json

this is ahdinosaurstlye-refactor with some tweaks from me .... looks like es2040 as well ..

Mixstyle refactor

---

modules_basic/compose.js
modules_basic/compose.mcss
modules_core/style-mixins.js
style.css

@ahdinosaur @mmckegg this is ready for a review

Compose refactor

---

h.js
modules_basic/about.js
modules_basic/avatar.js
modules_basic/compose.js
modules_basic/compose.mcss
modules_basic/message-author.js
modules_basic/message-backlinks.mcss
modules_basic/message.mcss
modules_core/style-mixins.js
modules_extra/network.js
modules_extra/network.mcss
package.json
style.css

@ahdinosaur , @mmckegg would love a review on this before merging. 
Looks like this :

Network refactor

---

modules_basic/avatar/edit.js
modules_basic/avatar/edit.mcss
modules_basic/avatar/profile.js
modules_basic/avatar/profile.mcss
modules_basic/feed.js
modules_basic/follow.js
modules_basic/follow.mcss
modules_core/style/mixins.js

A newly modularised Profile Page
features not pictured: 
- a description field (top right)
- followers, following (with smaller icons) 
- 
to develop still

Refactor profile

---

modules_basic/feed.js
modules_basic/index.js
modules_basic/message/confirm.mcss
modules_basic/message/render.mcss
modules_basic/private.js
modules_basic/public.js
modules_basic/scroller.js
modules_basic/scroller.mcss
modules_basic/setup.js
modules_basic/thread.js
modules_core/tabs.js
modules_extra/channel.js
modules_extra/git-ssb.js
modules_extra/notifications.js
modules_extra/search.js

@ahdinosaur would be interested in talking about this.
my motivations were : 
- extract Scroller as a module
- add styling to scroller, so that Message has border ONLY when it's a child of a Scroller
- hide some of the specific pickiness of the scroller setup.
what I've made is on the edge of not worth it ... but then the scroller code everywhere is a bit weird.
I think what I've done is a new pattern in a couple of ways : 
- I have a weird 'content' keyword to note the position of the content div to be created
- I'm introduced a meta-template / constructor which other templates are using...

Scroller module

---

message/html/compose.js

This fixes an issue where a subsequent reply would get stuck replying to the same post as the previous.
Possibly fixes other weird issues.
Corresponding fix in Patchwork: https://github.com/ssbc/patchwork/commit/6a4dd175b0e6195afeec9be9edf7a1e0723dfce0

fix compose overwriting observable meta

---

app/styles/css/font-awesome.js
package-lock.json
package.json

haven't actually tested this on `patchlite` yet, but might work :smiley:
https://github.com/ssbc/patchbay/issues/116

use `require-style` to require font styles in a patchlite friendly way

---

.gitignore
main.js
package.json

Hullo!
@mixmix you still interested in integrating this into patchbay?
There's probably more that needs to be done before this pull request can be merged, but I thought I'd open it early so we can start a conversation about what needs to be done for it to be ready to be merged :)

Introducing chess

---

README.md

From installing on a new node setup

Need electron and electro too

---

main.js
package.json

Doing it as a pull request as I want to make sure you agree :)

Add ssb-chess back in as it's been updated to integrate with the new router

---

app/html/app.js
main.js
package-lock.json
package.json

Save window settings

---

app/html/search-bar.js

Thought this would be more intuitive

On select from dropdown go directly to result, don't wait for enter

---

about/html/edit.mcss
app/page/thread.mcss
app/styles/mixins.js
contact/html/relationships.mcss
message/html/compose.js
message/html/compose.mcss
message/html/layout/default.mcss
package-lock.json
package.json

No large uploads

---

about/async/suggest.js
channel/async/suggest.js
message/html/compose.js

use some simple regex matching.
The has the effect of checking if the word typed occurs anywhere _within_ strings, as opposed to having to be right from the start.
e.g. `dino` will match ah**dino**saur
e.g. `cat` will match crying_**cat**

better mention search

---

about/async/suggest.js
app/html/suggest-box.mcss
channel/async/suggest.js
message/html/compose.js

Suggest with alias

---

about/html/edit.js
about/html/edit.mcss
app/html/external-confirm.mcss
app/styles/mcss/button.mcss
app/styles/mcss/lightbox.mcss
app/styles/mixins.js

copy in improvements from patch-profile

Better profile picker

---

app/html/app.js
app/html/filter.js
app/html/filter.mcss
app/html/scroller.mcss
app/page/channel.js
app/page/channel.mcss
app/page/page.mcss
app/styles/mixins.js
app/sync/initialise/settings.js
package-lock.json
package.json

Another candidate for saving. I use Only people I follow a lot and don't have to turn it on every time I start the app :)

save filters

---

contact/html/relationships.js

display who a profile is blocking, as well as who they are blocked by

---

app/page/channel.js
app/page/private.js
app/page/public.js
app/page/thread.js
main.js
message/html/compose.js
package-lock.json
package.json

This is duplicate of https://github.com/ssbc/patchbay/pull/161 except on a branch in this repo.
I intend to make a couple of tweaks before merging

add automatic draft saving to composer (local branch)

---

app/html/filter.js

Some people are know to be quite chatty on the private channel :smile: @Happy0 
<a href="https://ibb.co/kCHNMc"><img src="https://thumb.ibb.co/kCHNMc/chatty_chap.jpg" alt="chatty chap" border="0" /></a>

Add show private filter

---

main.js
message/html/action/quote.js
message/html/compose.js
post-patchcore/message/html/action/quote.js

This is mostly the work of https://github.com/gmarcos87. I had fun reviewing and grokking some more patchbay internals. Leaving it here in case others will find it useful.

Add quote button

---

app/html/scroller.js
app/html/scroller.mcss
app/html/tabs.mcss
app/page/channel.mcss
app/page/errors.js
app/page/thread.mcss
app/styles/mcss/button.mcss
app/styles/mixins.js
package-lock.json
package.json

This refactors the scrollers in preperation for adding mutant-scroll in more places.
Add the ability to add classList and className to scroller.
Also restyles the scroller using css-grid.
Adds new patch-inbox which also takes advantage of these styles

refactor scroller, styling

---

app/html/app.mcss
app/html/scroller.mcss
app/page/public.js
app/page/settings.js
app/styles/mcss/app-theme-vars.mcss
app/styles/mcss/hypertabs.mcss
app/styles/mcss/markdown.mcss
app/styles/mcss/scrollbar.mcss
app/styles/mixins.js
message/html/action/likes.js
message/html/layout/default.js
message/html/layout/default.mcss
message/html/layout/mini.mcss
package-lock.json
package.json

This is a start of adding what are basically CSS variables.
It's going to make theming or choosing your own color scheme super easy!
There's more I'm going to do, but I think it would be good to merge what I've done so far

styles remix

---

app/page/calendar.js

Changes to make it so that /calendar is available in the menu far right.
This is really a request for comments, it seemed to work for me; But was not really sure I was doing things "right".

Add calendar to menu items

---

app/page/blogs.js

Fix blog by requiring `app.sync.goTo`

---

app/html/settings/accessibility.js
app/html/settings/accessibility.mcss
app/html/settings/custom-styles.js
app/html/settings/custom-styles.mcss
app/page/imageSearch.mcss
app/page/page.mcss
app/page/settings.mcss
app/sync/initialise/settings.js
app/sync/initialise/styles.js

accessibility v1

---

app/html/menu.js
app/page/blogs.js
app/page/calendar.js
app/page/imageSearch.js
app/page/notifications.js
app/page/posts.js
app/page/private.js
app/page/profile.js
app/page/public.js
app/page/query.js
app/page/settings.js
message/html/meta/unread.js

**This PR sorts the menu alphabetically, and removes the inline `order` styles.** I spent about an hour banging my head against the Mutant documentation when I realized my sorted array wasn't showing up correctly in the UI, but after removing the inline `order` CSS everything works great.
I'm still learning both depject and Mutant, so please let me know if there's a more idiomatic way to do this. I'm not sure whether `app/html/menu.js` is the best place for `sortByProp`, maybe it should go somewhere else? I'd appreciate suggestions and/or a review!
---
For future archaeology, I found https://github.com/mmckegg/mutant/issues/6 to be a great jumping off point for learning to sort observables with Mutant and Patchbay. I don't think I'd have the intuition to use `computed()`, so I'm hoping …

Sort menu alphabetically

---

app/sync/catch-keyboard-shortcut.js

Fix keyboard shortcut scroll error

---

contact/html/relationships.js
message/html/compose.js
message/html/render/about.js

Just noticed a few small linter errors that were making `npm test` fail. Should be good to go now!

Fix linter conformance issues

---

message/html/compose.js
message/html/compose.mcss
package-lock.json
package.json

this is a courtesy PR
y'all should know I've extracted and refactored a bunch of the blob creating logic.
I plan to also open a PR upstream in patchcore.
I'd like to make [**ssb-blob-files**](https://github.com/ssbc/ssb-blob-files) the thing we all maintain and add to

add ssb-blob-files (to replace blob.html.input)

---

config.js

not sure who added this sockets stuff but it's breaking the windows installers D:
This is a temp fix which should work
cc @cryptix @arj03 @christianbundy

dont add sockets for windows at the moment

---

app/page/network.js

Resolves #289 
I think I'm the only one who needs this dep because others are using keyboard shortcuts that don't trigger click events.

Fix network page with missing depject dep

---

app/html/settings/tor-only.js
config.js
package-lock.json

Now that tor is working inside electron, I can finally merge this :)

Add tor only mode to settings

---

package-lock.json
package.json

This fixes some bugs (specifically for LAN sync) that brings behavior of this library closer to ssb-gossip
cc @arj03

update ssb-legacy-conn to 1.0.23

---

package-lock.json
package.json

So I think this is about ready to go. A lot of the styling is blatently stolen from gatherings and could use its own identity but there is already a *lot* of new stuff here ;-)

Scuttle book

---

README.md

This pull request is a part of the documentation drive and still a work in progress.

documentation drive

---

app/async/catch-link-click.js
app/sync/initialise/dat.js
message/html/compose.js
message/html/compose.mcss
package-lock.json
package.json

This should be ready to go I think. What it does is use the [dat-shared-files](https://github.com/arj03/dat-shared-files) module I created to make it easier to share files with dat. The integration into patchbay opens dat links as external links, so should open in beaker browser.
Would love for someone to give this a spin before merging :-)

Support sharing files using dat

---

app/page/notifications.js
package-lock.json
package.json

I wanted to keep the code for pulling the notifications seperate, so it could be tested. So this is mostly a pull-merge :)

Add book notifications

---

app/html/scroller.js
app/html/settings/default-tabs.js
app/html/settings/friend-hops-graph.svg
app/html/settings/friend-hops.js
app/html/settings/friend-hops.mcss
app/html/settings/friend-pub.js
app/html/settings/remove-exif.js
app/html/settings/tor-only.js
app/html/settings/zz-version.js
app/page/settings.js
app/page/settings.mcss
package-lock.json
package.json

@marylychee I took the liberty of adding you to the SSBC org (you may have to accept), and pulling your branch into the repo here so that I could start a WIP PR that we could look at and more easily discuss and jam on

WIP - slider for hops!

---

app/html/app.mcss
app/styles/mcss/markdown.mcss
app/sync/initialise/styles.js

Fixes https://github.com/ssbc/patchbay/issues/360
Implements @christianbundy's suggestion for a fix. Needs some changes in patchcore as well, I'll submit that pr in a minute.

Fix weird emoji font issues
