modules/channel.js, modules/index.js, sbot-api.js
pulled out of #8
This adds a screen_view for channels (tab paths starting with '#'),
and adds a message_meta for messages to indicate their channel.
Performance of loading channel tabs is improved significantly by dominictarr/ssb-query#1
=> Add channel view

README.md, modules/channel.js, modules/index.js, modules/search-box.js, modules/search.js, modules/tabs.js, modules/thread.js, sbot-api.js, style.css
This adds search, including a message view where a path for a search query starts with a '?', and a keybinding of '/' to activate the search field. The search is basically a grep of the log, like how Patchwork and git-ssb-web do it.
Also I did a minor refactor of how keyscroll is used, and other minor changes.
Currently search causes patchwork/sbot's CPU usage to go high for a while, I think because the operation reads the whole log and muxprc doesn't pass through the backpressure. I think I might be able to work around this by using `u.next()` to combine multiple requests with `limit: N` instead of doing an unlimited request and `take(N)`. Also, if a search query returns no results, the use of `u.next()` triggers the query to be repeated after the stream ends, even after the search tab …
=> WIP: Search & stuff

modules/search.js
@clehner more search stuff.
matches on exact word boundries and supports multiple search terms.
this makes search quite a bit more useful.
i'm not 100% sure about using exact word boundries, but it should probably be the default.
I tried to search for number5's post about address-something. I rememebered the word "address",
but i didn't remember it was "addressable" maybe the answer is globbing? `address*`?
or maybe stemming? but is there a language agnostic way to do stemming? (guessing maybe with markov chains?)
I'm quite impressed with how well brute force search is working!
Also, I'm noticing that feeds + keyboard scroll, and suggest + keyboard select is very similar. we could make these all use the same modules, and if we had a compact way to render a message, have …
=> search respects word boundries and multiple terms

modules/avatar-profile.js, style.css
I think this looks better.
i think the next thing is the ID input is ugly. That could be a "copy id" option like patchwork has,
or also there could be a header that appears on the message view (i.e. the thread page) which would have a selectable input box.
=> Right align message metadata

modules/timestamp.js
Once a minute re-render all timestamps on the page.
Show full datetime string in `title` tooltip.
This makes it easier to tell when things were posted.
=> Keep timestamps up-to-date

modules/like.js, modules/message.js, style.css
I changed yups to digs for consistency across the three apps, Patchwork/git-ssb-web/Patchbay. Feel free to reject if yup is preferred. 
In the future perhaps the deployer can set this to 'Star' or 'Yarr' in a config file?
WIP commit. Next I'm going to try to get voting into the bottom right corner of the screen. Next next I'm going to try to get a reply button down there too.
Ok this is mostly accomplished. The one goal I have is to remove the ' | ' when there is no dig button.
=> yups to digs, digs to bottom right corner

index.js, modules/_screen_view.js, modules/index.js, modules/split.js, modules/tabs.js, package.json
this adds basic support for split views.
as you'll notice from looking at the commits, this was very simple to implement!
since we had previously made sure that each module was well behaved, and since we used flex box, and the width is reactive... it just worked! ;)
=> Split view

modules/like.js, style.css
This is what I meant to accomplish yesterday with a '|' character. I figured out that it's easier to accomplish with css!
=> add space and separator between Dig and Reply

.gitignore, modules/audio-mp3.js, modules/index.js, modules/meta-image.js, modules/music-release-cc.js, modules/music-release.js, music-release.json, music-tracks.json, package.json
This adds two approaches for adding music to patchbay:
* `music-release-cc.js` displays `type: music-release-cc` posts (like `%e/JG0Stf90f4FBpBSPC+OAwl5EAIL5Xz3LFz0mhgpl8=.sha256`)
* `music-relase.js` and friends which depend on (`root`,`branch`)  linked `meta-image`, `audio-mp3` type posts to aggregate a release. I linked some examples of this in `%KgIliFBy5MeXafVENTNkRVHdFTy+d+T2zGSy9EuSYBg=.sha256`)
Visually I like the first approach more but dislike the _fat_ objects it uses. The 2nd approach gives you the option to dig/pin/star/whatever individual tracks/meta and recompile them in playlists for instance.
=> stabbing in the dark

index.js, modules/app.js, modules/index.js, modules/tabs.js
This PR reorganizes how the current state is managed.
it makes tabs.js just another screen_view, and means that you can you could say,
link some one directly to an invite code, instead of just sending them a url,
and then asking them to paste an invite code.
it also means you can open a tabs view as a tab recursively! although the keyboard shortcuts don't work quite right (still control the top level tabs) and I've had to disable saving the state in localStorage, that will just have to get a little bit smarter.
=> WIP: use hash for 'routing'

modules_core/message-confirm.js
fixes `depject` error when smoke testing https://github.com/dominictarr/depject/pull/9
=> depject gives: use true instead of "true"

modules_basic/markdown.js, modules_basic/markdown.mcss
Mainly added this to style the blockquote.
Feels like a nice clean easy way to add styles safely to markdown chunks.
Does ssb-markdown bring any styles in with it ?
=> add Markdown mcss

modules_basic/avatar/image.js, modules_basic/compose.js, modules_core/index.js, modules_core/search-box.js, modules_core/suggest-box.css, modules_core/suggest-box.js, modules_core/suggest-mentions.js, modules_core/tabs.js, modules_extra/channel.js, package.json, style.css
~~extract suggest logic into `built_suggest_box` and add some sweet styling~~
[EDIT]
**Context** :
We're using a module called `suggest-box`, which is responsible for the text-complete suggestions on a few types of mentions in the compose + search inputs.
This pull request : 
- adds images to @-mention and emoji-mention type suggestions
- takes advantage of suggest-boxes small text feature to space out the @-mention info
- extracts the suggest-box specific styling into a tighter (specificity) and clearer css module
- extracts a generic `suggest_box_builder`
=> extract suggest-box into a helper module which builds suggest boxes

app/styles/css/global.js
The emojis are quite big all of the sudden when running with npm start. This makes them the same size as the text. Not sure if the other things was a feature or not, but I like them smaller :)
=> Fix the size of emojis

app/html/page/private.js, app/html/page/public.js
_**Untested**_
The looping feed problem was caused by patchcore changing to use asserted ordering for `feed.pull.public` and `feed.pull.private`. 
`nextStepper` was sending the wrong `lt` value when requesting the next batch.
**This PR manually sets the correct next step key for these feeds.**
---
Interesting to note is that `feed.pull.channel` also changed to asserted ordering, but patchbay isn't using `nextStepper` for this, so was unaffected. You could probably remove `nextStepper` from everything. I suspect it was only there to make the lite client work better.
=> fix infinitely looping public and private feeds since patchcore update

package.json
I just noticed that patchbay is not generating _channel mentions_. This means that posts like [this one](https://viewer.scuttlebot.io/%250q9iOAgBixNFjeLO1UZefzCX1Xsv09Pl2C%2Fl2ACjDQQ%3D.sha256) won't show up under the mentioned channels. 
This is because it is using an old version of `ssb-mentions`. PR updates to the latest version.
=> bump ssb-mentions for channel hashtags

about/html/edit.mcss
Seems to be white on white. Not sure how it was broken, but this seems to fix it.
=> Fix invisible confirm button for changing names

background-process.js, package.json
This version of ssb-chess does not require sqlite3. Instead, it uses `flumeview-reduce` in the `ssb-chess-db` scuttlebot plugin.
Before this is merged I'd like someone to test / try out the following:
* Send me a game invite and tell me you've done so I can make sure 'received' invitations are still displayed.
* Make sure the 'observe' tab still looks sensible.
* Make sure the 'my moves' and 'games' tabs still look as you expect.
* View a player's profile and make sure the list of finished games look sensible.
=> Use new version of ssb-chess which does not require sqlite3

app/page/notifications.js
I got sick of reading redundent messages in `/notifications`
This is a mini PR which filters out : 
- messages I authored
- messages that are private (which are already in `/private` or `/inbox` which I view as their own dedicated notification area)
I'm going to merge this straight off because it feels small, but happy to discuss. I think notifications need a whole feature built around them in the future, so expect this to be scrapped
cc @Happy0 @arj03 ... who else needs to know?
=> remove PMs + my posts from /notifications

README.md, app/html/app.js, app/html/tabs.js, index.js
Tab keyboard shortcuts like Chrome or Firefox
I couldn't prove that windows has a different `Window` menu, if I'm wrong I'm happy to put back the conditional.
Chrome and Firefox has their tab controls under `File` but that seems weird here. Also I'd love to bring in a new tab window but that's a completely new view and I have no idea what it might look like. Additionally I'd love to do an undo close tab but I'm not sure how we'd want to keep history.
=> Add keyboard tab controls

app/html/filter.js
fixes #178 
This would only affect new users, so that's probably why I got it! There was a setting that was being read before it was written to, causing the following error:
```
base.html:19 TypeError: Cannot read property 'exclude' of undefined
at Object.Filter (/Users/matt/Code/patchbay/app/html/filter.js:37:32)
at Object.filter (/Users/matt/Code/patchbay/node_modules/depject/apply.js:15:30)
at Array.publicPage (/Users/matt/Code/patchbay/app/page/public.js:41:88)
at Array.<anonymous> (/Users/matt/Code/patchbay/node_modules/depject/apply.js:15:30)
at /Users/matt/Code/patchbay/node_modules/patchcore/router/sync/router.js:29:31
at Object.nest (/Users/matt/Code/patchbay/node_modules/patchcore/router/sync/router.js:20:12)
at Object.router …
```
=> #178 - fix white screen on startup (caused by missing default filter)

app/html/filter.js, app/html/filter.mcss
hey @arj03 here's me putting the user filter back in. It doesn't persist like the others.
I've also added a 'root' filter, which was a feature requested by a colleague - basically it lets you just review the heads of the threads to find things again a little more easily
=> re-add user filter, add root-only filter

package-lock.json, package.json
I'm having an issue with an old version of `sodium-native` which:
1. Doesn't recognize that I already have libsodium.
2. Is missing a critical file because of a [silly error](https://github.com/sodium-friends/sodium-native/issues/43#issuecomment-345478719).
This PR is the result of running [`npm update`](https://docs.npmjs.com/cli/update). Once this is merged I'll be able to get [`patchbay-git`](https://aur.archlinux.org/packages/patchbay-git/) working with native crypto. :business_suit_levitating:
=> Run `npm update` to bump `sodium-native`

contact/html/relationships.js, message/html/compose.js, message/html/render/about.js
This removes `when()` from being used on values that are non-observable, replacing them with a ternary function that does the same thing **except that it doesn't execute both branches**. This means that it resolves #231 without treating just the symptoms (like #232). We *may* be able to replace `undefined` with `null`, but in an effort to keep things from breaking I've matched `when()`'s behavior exactly.
=> Remove when() on non-observables

app/sync/initialise/settings.js
This PR means that future versions will default to opening `/posts` rather than `/public` when the application is opened with no "default tabs" customization. This will not effect users who have customized this to their liking.
It's worth mentioning that this is likely a personal preference, so if it's not a good candidate for `master` then I don't mind closing this at all. Also, if there are any unresolved bugs in `/posts` I'd be happy to take a look at them before merging is considered.
=> Replace /public with /posts in default tabs

app/styles/mcss/markdown.mcss
I noticed that h3 elements are bigger than h2 elements, which is caused by a typo regarding `em` sizing versus `rem` sizing. Infinitely trivial.
=> Fix `Markdown > h2` font-size

package.json
Hey @Happy0! I've noticed you've been bumping this manually, so I figured I might just add a `^` to match `1.x.x`.
=> Allow future ssb-chess-mithril updates

index.js
In the current master of patchbay, you can close the main window on macOS and Patchbay continues to run in the background. However, when you click on the dock icon, nothing happens. The only way to show the main window again is to right click, quit, and then relaunch.
**This PR adds an `on('activate')` handler that shows the window again.**
This is safe to merge as it mostly just brings the patchbay `index.js` inline with the patchwork one.
=> fix reopening main window on macOS

assets/base.html
cc: @mixmix @cryptix I figured it out!
Resolves #252 
Prepended "Error " in each nested object, for unknown reasons.
```
Error {
key: '%WAqQoKWBkL20Hd2wUUTh6u8E9CcrW7E+OJTUEo7LYWQ=.sha256',
value:
Error {
previous: '%dwAq7w5F9iAMCKVz9X0kOMxGkjlENOO6vJLcdcJFohc=.sha256',
author: '@+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=.ed25519',
sequence: 6654,
timestamp: 1540829857167,
hash: 'sha256',
content: Error { type: 'vote', channel: 'ssb-dev', vote: [Error] },
signature:
'4552sjoQfjE7HKS0mmxVrmvzKPh+BwN1qNS5VeAlz7sZYslGjH+wC9kj6/0y4h/DlpJSpLF98sTEjH4mDh9DDw==.sig.ed25519' },
timestamp: 1540829857186 }
```
Normal JS output with pretty-print (and coloring in Electron 3).
```js
{ key: '%V7gfMPLT3dpPBB5ToNJiZA3lCW849Cew9XvXboZUJPM=.sha256',
value:
{ previous: …
```
=> Send logs to stdout with console require

app/page/posts.mcss
Following on from the discussion in #300, this lightens up the link colors for the black background posts.
I'm unclear if this color is desirable when the 'invert colors' thing is toggled. I've included screenshots to show each option.
Fixes #293
=> Use the known 'light purple' color for links on main posts.

config.js
`local/private` scope is the local network, i.e. wifi. _not_ localhost. that is the `device` scope.
A unix socket can only be connected to within the device.
This will fix https://github.com/ssbc/ssb-server/issues/640
I'm not really happy with the scope names. It seems like a confusion as to meaning of the names lead to this bug..
I'd kinda lead towards "device" "nearby" "global" or something. get away from networking terms?
=> fix device scope

app/page/thread.js, message/html/render/about.js, router/async/normalise.js
With this, we can now read super secret messages posted as links with an unbox key. See this message for two examples: %yTo0gv+o7dkJ0vn5K6FHh+q/6ZJbIghboSOFNlm+wLE=.sha256
=> Support links with unbox key

README.md
this avoids .git suffix in default working copy path.
=> README: drop .git from clone url
